### PR TITLE
Desing smash

### PR DESCRIPTION
**Pull request by SigmaSam**

### CODE REVIEW

**Review by trekab — COMMENTED** [review]
Hello @SigmaSam and @jacobo12montes, It is unfortunate that I have to mark your code review request as invalid because your pull request lacks a short summary of the changes introduced. Check out this [guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) from the pathwright, make the necessary changes, and submit another code review request.

__Treasure Kabareebe__

**Comment by jacobo12montes** [comment]
Make the Smashing Magazine
-Create the skeleton with all the elements
-Position the elements and give it  a size
-Give it a background
-Put the style and fonts necessary 
-Check the linters and HTML validator

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @SigmaSam and @jacobo12montes, your project looks great :+1: Great effort with this project :slightly_smiling_face: However before we proceed, we need to address the following comments. Kindly check the comments below:

- Kindly enable the stickler by visiting the stickler-ci.com. By not enabling a stickler could cause the project to be marked as invalid as with the PR description pointed out by the previous TSE. [Link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)
- Kindly fix the horizontal scroll, A quick fix would be to set the width to 100% so that, no matter your screen size, the app will fix as required
- Kindly wrap each of the nav items with a ```<div>``` as in the images below
na
- Kindly apply the DRY rule, we can refactor our CSS code so we avoid repetition as in the images below. Not only this, kindly go through the code and find all repeated code
fac

[OPTIONAL]
Going forward, our commit messages must always be in the present, for example, ```add``` instead of ```added```

Kindly make these changes and submit another code review request :smile: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

**Comment by SigmaSam** [comment]
Fixed the linter conflicts.
Removed the Horizontal Scrolling as required.

**Comment by SigmaSam** [comment]
-Fixed linter conflicts.
-Removed the horizontal scroll.

Hopefully, this is complete now, but by all means please let us know if there is something else we should do.

**Review by trekab — CHANGES_REQUESTED** [review]
# Changes Required!
Hi @SigmaSam and @jacobo12montes! Impressive job on this project! :+1: However, there are a few changes you need to make to complete. These are;

- [x] All the elements and element's backgrounds and font colors should be grayscale color (black, white, or any shade of gray), this rule also applies to images([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/design_teardown/grayscale_requirement.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/design-teardown)).

## Optional:
- [x] Your `main` tag is doing the exact function of the `body` tag. Use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of the document. Usually, the main page `footer` and `nav` appear outside the `main` tag.
- [x] It is a good idea to try out the [CSS validator](https://jigsaw.w3.org/css-validator/) for your CSS.

__Kindly work on the suggested changes and submit another code review request.__
_Feel free to contact me on slack for any questions about this review_ :wink: 
__Treasure Kabareebe__

**Comment by jacobo12montes** [comment]
We haved changed the background color of some elements as the  TSE request

**Review by trekab — APPROVED** [review]
# Approved! :tada: 
Congratulations! You may merge to master.

Happy coding! :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Pull request merged**
